notifications:
  slack: cuencafinance:6N0IaVciA0KyNylSTq5ZzW4I

language: python

script: make test

jobs:
  include:

    - stage: test
      python: 3.6
    - stage: test
      python: 3.7
      dist: xenial
      sudo: true
    - stage: code coverage
      python: 3.7
      dist: xenial
      sudo: true
      install: pip install coveralls
      script:
      - coverage run --source=stpmex setup.py test
      - coveralls
    - stage: PyPI Upload
      python: 3.7
      dist: xenial
      sudo: true
      script: echo "Uploading packages to PyPI"
      deploy:
        provider: pypi
        user: cuenca
        password:
            secure: "CipKYamnKFQyhAuyic1zOMpraQf2/3MUcOhw6bJxwGkw9Dkek36XzAi2a/qgnwtZzfnhKc66yyU1p9g7JCURQ4CW3Kr7n3HC0czHt03MENtmZo8XfrQobeOm1MjmaGYEZYpx/U9Uo+zENajl23eq9kq1Da5jNw2rNJIvq/O5vRecCInq409USzAnDPl1SeKlufaysH6mf8m8pvVzS4zR0WHPmK5q0TsphB6rqc/8LuU7ALZN6O4LBHRI/q4Y2lk2AsaeIHYEM0Zyu5RaV66SaqV2tV0PDjPFKyM/UXP/TZdUrWp1KrKnLYOPoGgV4beFOEEoY3EDfQ0cmaNTV8CL9TOhM/r/9TQwz9RWTP0UzWt9UqifYF1BRk6aRsFrNOug4w4r5GvwVU/xnslIAv795y3Za1NNyCtNuvhftraZjFvzygBCcqhmj3zUmoDvaJiKR4vLhtZjH6ph/v4p+4SWf8oS74UwtQXXtiSBinXtKiwVKE7woupERgb0+2WTndoX8AZk39fz+SGFdaPYMpHoNRiSLw3DLaQeRoC5UVXs9mtd3/HlxVKj7YGhdUaSaZ5JtYUWizjd/m9DPlM3Alyr020gqO/q9F/hHjcWMELcMML0g0lkMjqtCv4esusDh9YJy+rmuiUpehStqY5KMOhxjP3S2HN4G6o1XHOc6xYWoWo="

        on:
          tags: true
        distributions: sdist bdist_wheel
